### ISSUE TITLE
AbortController is not defined

### ISSUE THREAD

**Issue by decito** [Ryheff24/Massdiscordunban#3]
$ node index.js
(node:9936) UnhandledPromiseRejectionWarning: ReferenceError: AbortController is not defined
    at RequestHandler.execute (Massdiscordunban-main\node_modules\discord.js\src\rest\RequestHandler.js:172:15)
    at RequestHandler.execute (Massdiscordunban-main\node_modules\discord.js\src\rest\RequestHandler.js:176:19)
    at RequestHandler.push (Massdiscordunban-main\node_modules\discord.js\src\rest\RequestHandler.js:50:25) 
    at async WebSocketManager.connect (Massdiscordunban-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:128:9)
    at async Client.login (Massdiscordunban-main\node_modules\discord.js\src\client\Client.js:245:7)

**Comment by decito** [comment]
Remember to update node and npm version, everyone!
